name: 'Exchange Api'
description: 'Exchange-API-with-Composite-Action'

runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Remove and push changes
      run: |-
        git config user.name "Phanuel Mutuma"
        git config user.email "phanuelmutuma@gmail.com"
        git rm usd.json kes.json ngn.json
        git commit -m "Removing Files..."
        git push
      shell: bash
    - name: Download USD Feed
      run: |-
        curl -X GET https://v6.exchangerate-api.com/v6/65053376ce6023bfbbacaeb2/latest/USD -o usd.json
      shell: bash
    - name: Download KES Feed
      run: |-
        curl -X GET https://v6.exchangerate-api.com/v6/65053376ce6023bfbbacaeb2/latest/KES -o kes.json
      shell: bash
    - name: Download NGN Feed
      run: |-
        curl -X GET https://v6.exchangerate-api.com/v6/65053376ce6023bfbbacaeb2/latest/NGN -o ngn.json
      shell: bash
    - name: Commit and push changes
      run: |-
        git config user.name "Phanuel Mutuma"
        git config user.email "phanuelmutuma@gmail.com"
        git add usd.json kes.json ngn.json
        git commit -m "Updated Today..."
        git push
      shell: bash
      
